// <auto-generated />
namespace ITI.Mvc.LinkedIn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class usereducation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(usereducation));
        
        string IMigrationMetadata.Id
        {
            get { return "201903051610246_usereducation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
