// <auto-generated />
namespace ITI.Mvc.LinkedIn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class companiesmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(companiesmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201903020806428_companiesmigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
